// <auto-generated />
namespace DoAnFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class V3Migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V3Migration));
        
        string IMigrationMetadata.Id
        {
            get { return "202109271600047_V3Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
